In [1]:
import numpy as np


In [2]:
arr = np.full((2,3), 7)

In [3]:
arr

array([[7, 7, 7],
       [7, 7, 7]])

In [4]:
arr = np.full((2,3), [1,2,3])

In [5]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
arr = np.random.rand(5,3)

In [9]:
arr

array([[0.76557155, 0.3038033 , 0.44197666],
       [0.61418935, 0.42211326, 0.62201062],
       [0.88621786, 0.8242337 , 0.96986694],
       [0.80423225, 0.80497852, 0.75920063],
       [0.76186463, 0.10323157, 0.85904897]])

In [13]:
a = [1,2,3,4,5]

arr= np.random.choice(a, (10,10), replace=True, p=[0.3,0.2,0.05,0.05,0.4])

In [14]:
arr

array([[2, 5, 5, 4, 1, 1, 2, 5, 1, 3],
       [5, 1, 2, 5, 1, 5, 2, 2, 1, 5],
       [5, 2, 1, 1, 1, 5, 2, 5, 5, 1],
       [5, 2, 5, 5, 1, 2, 1, 4, 1, 5],
       [2, 1, 5, 5, 5, 2, 5, 5, 5, 5],
       [5, 2, 5, 5, 2, 1, 5, 1, 2, 2],
       [5, 2, 1, 1, 1, 5, 1, 1, 5, 1],
       [2, 1, 2, 5, 2, 2, 1, 5, 2, 1],
       [1, 2, 1, 1, 5, 5, 2, 2, 1, 1],
       [1, 5, 5, 5, 1, 1, 1, 5, 1, 5]])

In [12]:
a

[1, 2, 3, 4, 5]

In [15]:
a = ['T', 'F']

arr= np.random.choice(a, (10,10), replace=True, p=[0.8,0.2])

In [16]:
arr

array([['T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'T', 'F', 'T', 'T', 'T', 'T', 'T', 'F', 'F'],
       ['F', 'F', 'T', 'F', 'T', 'F', 'T', 'T', 'F', 'T'],
       ['T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T'],
       ['F', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'T', 'T', 'T', 'T', 'F', 'T', 'T', 'T', 'T'],
       ['T', 'F', 'T', 'F', 'T', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'T', 'T', 'T', 'T', 'T', 'F', 'F', 'F', 'T'],
       ['T', 'T', 'F', 'T', 'F', 'T', 'T', 'F', 'T', 'T'],
       ['T', 'T', 'T', 'F', 'T', 'T', 'T', 'F', 'T', 'F']], dtype='<U1')

In [17]:
a = ['T', 'F']

arr= np.random.choice(a, (10,10), replace=False, p=[0.8,0.2])

ValueError: Cannot take a larger sample than population when 'replace=False'

In [18]:
arr = np.random.randint(0,10,(2,3))

In [19]:
arr

array([[2, 8, 5],
       [5, 7, 6]], dtype=int32)

In [20]:
arr = np.random.randint(0,10,(10,10))

In [21]:
arr

array([[9, 4, 3, 8, 2, 2, 4, 4, 3, 5],
       [9, 5, 9, 0, 7, 7, 0, 5, 3, 4],
       [4, 7, 6, 6, 8, 8, 4, 2, 7, 5],
       [6, 6, 0, 8, 2, 4, 4, 0, 2, 0],
       [7, 6, 7, 1, 5, 7, 4, 4, 1, 9],
       [7, 9, 1, 2, 4, 4, 3, 2, 6, 1],
       [3, 8, 5, 4, 3, 0, 3, 1, 8, 1],
       [8, 2, 3, 0, 2, 0, 5, 6, 5, 6],
       [4, 4, 0, 3, 0, 4, 5, 4, 9, 6],
       [2, 7, 6, 3, 6, 8, 7, 1, 5, 0]], dtype=int32)

In [53]:
arr = np.random.randint(5,10,6)
arr

array([9, 9, 5, 5, 8, 9], dtype=int32)

In [46]:
arr

4

In [28]:
a = [1,2,3,4,[5,6,7],8,9]
a

[1, 2, 3, 4, [5, 6, 7], 8, 9]

In [37]:
a[4][0:3] 

[5, 6, 7]

In [31]:
a

[1, 2, 3, 4, [5, 6, 7], 8, 9]

In [39]:
print(arr)

[7 5 9 9 8]


In [40]:
arr[2]

np.int32(9)

In [55]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [58]:
arr[0:1,0:2]

array([[1, 2]])

In [60]:
arr = np.array([12,13,4,5,45,47,23,31,25,89])
print(arr[arr<20])

[12 13  4  5]


In [61]:
a = [1,5,9]
arr[a]

array([13, 47, 89])

In [62]:
print(arr<20)

[ True  True  True  True False False False False False False]


In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [65]:
c =  a + b
c 

array([5, 7, 9])

In [66]:
c =  a - b
c 

array([-3, -3, -3])

In [67]:
a

array([1, 2, 3])

In [68]:
b

array([4, 5, 6])

In [69]:
c =  a * b
c 

array([ 4, 10, 18])

In [70]:
c =  a / b
c 

array([0.25, 0.4 , 0.5 ])

In [71]:
c =  a % b
c 

array([1, 2, 3])

In [72]:
c =  a ** b
c 

array([  1,  32, 729])