Attributes of Array

In [3]:
import numpy as np

In [4]:
import numpy as np

data = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(data)
data

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
print(np.shape(data))

(2, 2, 2)


In [6]:
print(np.ndim(data))

3


In [7]:
print(np.size(data))

8


In [8]:
print(data.dtype)

int64
