In [12]:
import numpy as np
data = np.array([10,20,30,40])
print(np.mean(data))

25.0


In [13]:
import numpy as np
data = np.array([10,20,30,40])
print(np.mean(data))

25.0


In [14]:
import numpy as np
data = np.array([10,20,30,40])
print(np.median(data))

25.0


In [15]:
import numpy as np
from statistics import mode


data = np.array([10,20,20,30,30,30,40])
print(mode(data))

30


In [16]:
import numpy as np

data = np.array([
    [10,20,30,40],
    [50,60,70,80]
])

print(data.ndim)
print(np.sum(data ,axis=0) )

2
[ 60  80 100 120]


In [17]:
import numpy as np

data = np.array([[
    [10,20,30,40,50,60],
    [40,80,90,70,50,10],
    [30,40,60,80,98,90]
]])

print(data.ndim)
print(np.sum(data , axis=1))

3
[[ 80 140 180 190 198 160]]


In [18]:
import numpy as np
data = np.arange(1,10)
print(data)

[1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np
data = np.arange(1,10)
print(data[::-1])

[9 8 7 6 5 4 3 2 1]


In [20]:
data=np.arange(1,10).reshape(3,3)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
data = np.array([[[[
    [10,20,30,40,50],
    [40,80,90,70,50],
    [30,40,60,80,98],
    [20,80,90,80,10],
    [40,39,10,30,20]
]]]])

print(data.ndim)


5


In [22]:
data = np.arange(1,26).reshape(5,5)
print(data)
print("\n")
print(data[1,2])
print(data[0,0])
print(data[4,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


8
1
25


In [23]:
data = np.arange(1,26).reshape(5,5)
print(data)
print("\n")
print(data[1,4])
print(data[3,3])
print(data[3,4])
print(data[0:2 , 1:3])
print(data[0:4 , 2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


10
19
20
[[2 3]
 [7 8]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]
