In [42]:
import numpy as np


In [43]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(data[0]+data[1])

[30 50 70 60]


In [44]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(data[0]*data[1])

[ 200  600 1200  800]


In [45]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(data[0]-data[1])

[-10 -10 -10  20]


In [46]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(20+data)

[[30 40 50 60]
 [40 50 60 40]]


In [47]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(np.square(data))

[[ 100  400  900 1600]
 [ 400  900 1600  400]]


In [48]:
print(np.sqrt(data))

[[3.16227766 4.47213595 5.47722558 6.32455532]
 [4.47213595 5.47722558 6.32455532 4.47213595]]


In [49]:
exponent = np.exp(data)
print(exponent)

[[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
 [4.85165195e+08 1.06864746e+13 2.35385267e+17 4.85165195e+08]]


In [50]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(np.square(data))

[[ 100  400  900 1600]
 [ 400  900 1600  400]]


In [51]:
data = np.array([10,20,30,40,50])
print(data*30)

[ 300  600  900 1200 1500]


In [52]:
data = np.array([10,20,30,40,50])
print(data+100)

[110 120 130 140 150]


In [53]:
data = np.array([10,20,30,40,50])
print(np.sum(data))

150


In [54]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(6,10).reshape(2,2)
print( a @ b)

[[22 25]
 [50 57]]


In [55]:
a = np.arange(1,7).reshape(2,3)
b =np.arange(1,10).reshape(3,3)
# print("b",b)
print( a @ b)

[[30 36 42]
 [66 81 96]]
