In [343]:
import numpy as np

In [344]:

arr=np.array([1,2,34,4,56,6,70,8,90,18,14,16,])
# np.reshape(arr,(3,4))
arr.reshape((4,-1))
arr.reshape((-1,4))

array([[ 1,  2, 34,  4],
       [56,  6, 70,  8],
       [90, 18, 14, 16]])

In [345]:
a = np.array([12,2,4,5])
b = np.array([5,7,92,0])

np.concatenate((a,b))

array([12,  2,  4,  5,  5,  7, 92,  0])

In [346]:
a = np.array([[12,2,4,5],[2,3,6,8]])
b = np.array([[5,7,92,0],[6,99,29,19]])

np.concatenate((a,b),axis=1)

array([[12,  2,  4,  5,  5,  7, 92,  0],
       [ 2,  3,  6,  8,  6, 99, 29, 19]])

In [347]:

np.concatenate((a,b),axis=0)

array([[12,  2,  4,  5],
       [ 2,  3,  6,  8],
       [ 5,  7, 92,  0],
       [ 6, 99, 29, 19]])

In [348]:

np.concatenate((a,b),axis=None)

array([12,  2,  4,  5,  2,  3,  6,  8,  5,  7, 92,  0,  6, 99, 29, 19])

In [349]:
np.unique(a)

array([ 2,  3,  4,  5,  6,  8, 12])

In [350]:
np.count_nonzero(b)

np.int64(7)

In [351]:
size = np.size(b)
count = np.count_nonzero(b)
print(size-count)

1


In [352]:
np.unique(b).size


8

In [353]:
np.unique_counts(b)

UniqueCountsResult(values=array([ 0,  5,  6,  7, 19, 29, 92, 99]), counts=array([1, 1, 1, 1, 1, 1, 1, 1]))

In [354]:
arr = np.array([0,0,0,6,72,8,0,8,801,0,0,0,0])
np.trim_zeros(arr)

array([  6,  72,   8,   0,   8, 801])

In [355]:
np.trim_zeros(arr,trim='fb')

array([  6,  72,   8,   0,   8, 801])

In [356]:
np.trim_zeros(arr,trim='f')

array([  6,  72,   8,   0,   8, 801,   0,   0,   0,   0])

In [357]:
np.trim_zeros(arr,trim='b')

array([  0,   0,   0,   6,  72,   8,   0,   8, 801])

In [358]:
a = np.copy(arr)

In [359]:
b = arr.view()

In [360]:
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50])

# Create a view
b = arr.view()

print("Original array:", arr)
print("View array:", b)

# Modify the view
b[2] = 99

print("\nAfter modifying the view:")
print("Original array:", arr)
print("View array:", b)

Original array: [10 20 30 40 50]
View array: [10 20 30 40 50]

After modifying the view:
Original array: [10 20 99 40 50]
View array: [10 20 99 40 50]


In [361]:
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50])

# Create a copy
c = arr.copy()

print("Original array:", arr)
print("Copied array:", c)

# Modify the copy
c[2] = 99

print("\nAfter modifying the copy:")
print("Original array:", arr)
print("Copied array:", c)

Original array: [10 20 30 40 50]
Copied array: [10 20 30 40 50]

After modifying the copy:
Original array: [10 20 30 40 50]
Copied array: [10 20 99 40 50]
