In [27]:
import numpy as np

In [28]:

arr=np.array([1,2,34,4,56,6,70,8,90,18,14,16,])
# np.reshape(arr,(3,4))
arr.reshape((4,-1))
arr.reshape((-1,4))

array([[ 1,  2, 34,  4],
       [56,  6, 70,  8],
       [90, 18, 14, 16]])

In [29]:
a = np.array([12,2,4,5])
b = np.array([5,7,92,0])

np.concatenate((a,b))

array([12,  2,  4,  5,  5,  7, 92,  0])

In [30]:
a = np.array([[12,2,4,5],[2,3,6,8]])
b = np.array([[5,7,92,0],[6,99,29,19]])

np.concatenate((a,b),axis=1)

array([[12,  2,  4,  5,  5,  7, 92,  0],
       [ 2,  3,  6,  8,  6, 99, 29, 19]])

In [31]:

np.concatenate((a,b),axis=0)

array([[12,  2,  4,  5],
       [ 2,  3,  6,  8],
       [ 5,  7, 92,  0],
       [ 6, 99, 29, 19]])

In [32]:

np.concatenate((a,b),axis=None)

array([12,  2,  4,  5,  2,  3,  6,  8,  5,  7, 92,  0,  6, 99, 29, 19])

In [33]:
np.unique(a)

array([ 2,  3,  4,  5,  6,  8, 12])