In [ ]:
import numpy as np 

In [95]:
arr = np.array([1,2,3,4,5])
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
import time 
n= 10

#lists
list1 = list(range(n))
list2 = list(range(n))

start = time.time()
result_list = [list1[i]+list2[i] for i in range(n)]
list_time = time.time() - start


# numpy arrays
arr1 = np.arange(n)
arr2 = np.arange(n)

start = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start

print(f"list time : {list_time:.6f} sec")
print(f"numpy time: {numpy_time:.6f} sec")
print(f"Numpy is apporaximately {list_time/numpy_time:.2f}x faster")



list time : 0.000418 sec
numpy time: 0.000087 sec
Numpy is apporaximately 4.79x faster


In [ ]:
import time 
n= 100

#lists
list1 = list(range(n))
list2 = list(range(n))

start = time.time()
result_list = [list1[i]+list2[i] for i in range(n)]
list_time = time.time() - start


# numpy arrays
arr1 = np.arange(n)
arr2 = np.arange(n)

start = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start

print(f"list time : {list_time:.6f} sec")
print(f"numpy time: {numpy_time:.6f} sec")
print(f"Numpy is apporaximately {list_time/numpy_time:.2f}x faster")



list time : 0.000180 sec
numpy time: 0.000079 sec
Numpy is apporaximately 2.27x faster


In [98]:
import time 
n= 10000


#lists
list1 = list(range(n))
list2 = list(range(n))

start = time.time()
result_list = [list1[i]+list2[i] for i in range(n)]
list_time = time.time() - start


# numpy arrays
arr1 = np.arange(n)
arr2 = np.arange(n)

start = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start

print(f"list time : {list_time:.6f} sec")
print(f"numpy time: {numpy_time:.6f} sec")
print(f"Numpy is apporaximately {list_time/numpy_time:.2f}x faster")

list time : 0.001291 sec
numpy time: 0.000120 sec
Numpy is apporaximately 10.79x faster


In [ ]:
data = np.array([1,2,3,4,5])
print(data)
data

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
data = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(data)
data

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
import numpy as np

data = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(data)
data

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Attributes

In [ ]:

print(np.shape(data))

(2, 2, 2)


In [ ]:
print(np.ndim(data))

3


In [ ]:
print(np.size(data))

8


In [ ]:
print(data.dtype)

int64


Array Creation functions

In [ ]:
#1)
np.zeros((2,3),np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
#2)
np.ones((4,4),np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
#3)
np.empty((2,2),np.int8)

array([[0, 0],
       [0, 0]], dtype=int8)

In [ ]:
#4)np.eye(n,m,k,dtype)
np.eye(3,5,1,np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

In [ ]:
#5)
np.identity(4,np.int8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [ ]:
#6)
np.arange(0,100,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
arr = np.arange(0, 100, 2).reshape(5, 10)
print(arr)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [ ]:
#7)np.linspace(start,end,number,endpoint,returnstep,dtype)
np.linspace(0.1,1,50,endpoint=True)

array([0.1       , 0.11836735, 0.13673469, 0.15510204, 0.17346939,
       0.19183673, 0.21020408, 0.22857143, 0.24693878, 0.26530612,
       0.28367347, 0.30204082, 0.32040816, 0.33877551, 0.35714286,
       0.3755102 , 0.39387755, 0.4122449 , 0.43061224, 0.44897959,
       0.46734694, 0.48571429, 0.50408163, 0.52244898, 0.54081633,
       0.55918367, 0.57755102, 0.59591837, 0.61428571, 0.63265306,
       0.65102041, 0.66938776, 0.6877551 , 0.70612245, 0.7244898 ,
       0.74285714, 0.76122449, 0.77959184, 0.79795918, 0.81632653,
       0.83469388, 0.85306122, 0.87142857, 0.88979592, 0.90816327,
       0.92653061, 0.94489796, 0.96326531, 0.98163265, 1.        ])