In [25]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
np.delete(matrix,6)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [27]:
np.delete(matrix,2)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [28]:
np.delete(matrix,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [29]:
np.delete(matrix,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])