In [145]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [146]:
np.delete(matrix,6)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [147]:
np.delete(matrix,2)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [148]:
np.delete(matrix,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [149]:
np.delete(matrix,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [150]:
np.delete(matrix,np.where(matrix>5))

array([4, 5, 6, 7, 8, 9])

In [151]:
np.insert(matrix,1,99)

array([ 1, 99,  2,  3,  4,  5,  6,  7,  8,  9])

In [152]:
np.insert(matrix,[1,2],[24,56])

array([ 1, 24,  2, 56,  3,  4,  5,  6,  7,  8,  9])

In [153]:
np.insert(matrix,3,[1,2,3],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [154]:
np.insert(matrix,3,[1,2,3],axis=1)

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [155]:
import numpy as np 
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9,]
              ])

arr1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9,]
              ])

np.intersect1d(arr,arr1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
import numpy as np 
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9,]
              ])

arr1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9,]
              ])

np.intersect1d(arr,arr1,assume_unique=True,return_indices=False)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])