1) Create a NumPy array
create an array containing numbers from 1 to 10


In [217]:
import numpy as np

In [218]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [219]:
data1 = np.arange(1,11)
data1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2) Check array properties
create an array and print : shape , size , data type , number of dimensions

In [220]:
data = np.array([[1,2,4,5,7],[9,8,7,2,1]])
print(data)
print()
print(data.shape)
print(data.size)
print(data.dtype)
print(data.ndim)

[[1 2 4 5 7]
 [9 8 7 2 1]]

(2, 5)
10
int64
2


3) Create a zeros array . 
create a 3x3 array filed with zeros

In [221]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

4) create a ones array . create a 4x2 array filed with ones

In [222]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

5) create an identity matrix . create a 5x5 identity matrix

In [223]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6) create a range array . create an array containing numbers from 10 to 50 with a step of 5

In [224]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

7) create evenly spaced values . create 11 evenly spaced numbers between 0 and 100

In [225]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

8) Reshape an array . create an array from 1 to 12 and reshape it into 3x4 matrix

In [226]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

9) Find the first element . create an array and print its first element

In [227]:
data = np.array([1,2,4,5,7,8])
print(data[0])

1


10) Find the last element . create an array and print its last element

In [228]:
data = np.array([1,2,4,5,7,8])
print(data[-1])

8


11) Slice an array . create an array from 1 to 20 and print elements from index 5 to index 10

In [229]:
data = np.arange(1,21)
print(data)
print(data[5:10])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10]


12) Reverse an array . create an array from 1 to 10 and reverse it

In [230]:
data = np.arange(1,11)
print(data[::-1])

[10  9  8  7  6  5  4  3  2  1]


13) Find maximum value . create an array and find its largest value

In [231]:
data = np.array([89,73,36,18,357,918,87])
print(data.max())

918


14) Find minimum value create an array and find the smallest value

In [232]:
data = np.array([89,73,36,18,357,918,87])
print(data.min())

18


15) Calculate sum . Find the sum of all elements in an array

In [233]:
data = np.array([89,73,36,18,357,918,87])
print(data.sum())

1578


16) calculate mean . Find the average of the array [10,20,30,40,50]

In [234]:
data = np.array([10,20,30,40,50])
print(data.mean())

30.0


17) Calculate median . Find the Meadian of [5,10,15,20,25]

In [235]:
data = np.array( [5,10,15,20,25])
print(np.median(data))


15.0


18) Find standard deviation . calculate the standard deviation . calculate the standard deviation 0f [5,10,15,20,25]

In [236]:
data = np.array([5,10,15,20,25])
print(data.std())

7.0710678118654755


19) Add two arrays
Add[1,2,3] and [4,5,6]

In [237]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

[5 7 9]


20) Multiply two array . Multiply[2,4,5] and [3,5,7] element wise

In [238]:
a = np.array([2,4,5])
b = np.array([3,5,7])

print(a*b)

[ 6 20 35]


21) Square of all elements . Create an array from 1 to 19 and find the square of every element

In [239]:
data = np.arange(1,11)
print(np.square(data))

[  1   4   9  16  25  36  49  64  81 100]


22) Find even numbers . Create an array from 1 to 20 and print only even numbers

In [240]:
data = np.arange(1,21)
data[np.where(data % 2 == 0 )]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

23) Count elements greater than 50 
Given [ 10, 25 , 60 ,75 ,30,90,45] count how many elements are greater than 50

In [241]:
data = np.array([ 10, 25 , 60 ,75 ,30,90,45] )
np.size(np.where(data>50))


3

24) Transpose a matrix . create [[1,2,3],[4,5,6],[7,8,9]] find the transpose

In [242]:
data = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
data.transpose()

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

25) Find the row wise sum . Given [[1,2,3],[4,5,6],[7,8,9]] find the sum of each row

In [243]:
data = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(np.sum(data,axis=2))

[[ 6 15 24]]


26) Bonus Challenge . Create a 5x5 matrix containing numbers from 1 to 25

In [244]:
data = np.arange(1,26).reshape(5,5)
data



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

27) Replace all add numbers in an array with -1

In [245]:
data = np.arange(1,21)
np.where(data%2!=0 ,-1,data)

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1,
       18, -1, 20])

28) Find all the numbers divisible by 3 in an array from 1 to 30

In [246]:
data = np.arange(1,31)
data[np.where(data%3==0)]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

29) Create a random array of 10 integer between 1 and 100

In [247]:
data = np.random.randint(1,100,10)
data

array([20, 23, 21, 28, 12, 99, 34, 58, 69, 50], dtype=int32)

30) Find the index of the largest element in an array

In [248]:
data = np.array([ 10, 25 , 60 ,75 ,30,90,45] )
data.argmax()

np.int64(5)