1)


In [60]:
import numpy as np

In [61]:
data = np.zeros((8,8))
data[1::2,::2] = 1
data[::2,1::2] =1

print(data)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [62]:
arr = np.zeros((8,8))

for i in range(0,8):
    if i%2==0:
        arr[i,::2]=1
    else:
          
         arr[i,1::2]=1
print(arr)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


2)

In [63]:
data = np.ones((5,5))
data[1:4 , 1:4] = 0

print(data)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


3)

In [64]:
data = np.array([5,12,7,18,25,3,15])
np.where(data > 10 , -1 , data)

array([ 5, -1,  7, -1, -1,  3, -1])

4)

In [65]:
data = np.arange(1,101)
data[np.where(data%3==0)]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

5)

In [66]:
# a = np.array([2,3,4,8,8,9])
# b = np.array([2,4,6,8,8,9])

# print(np.intersect1d(a,b))



6)

7)

8)

9)

10)