Create a NumPy array containing 10, 20, 30, 40, 50.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


Create an array of zeros.

In [2]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


Create an array of ones.

In [3]:
arr = np.ones((3, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create an array using arange().

In [4]:
arr = np.arange(5, 30, 5)
print(arr)

[ 5 10 15 20 25]


Create evenly spaced numbers.

In [5]:
arr = np.linspace(0, 20, 5)
print(arr)

[ 0.  5. 10. 15. 20.]


Find the shape of an array.

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


Find dimensions

In [7]:

print(arr.ndim)

2


Randomly choose an element.

In [ ]:
arr = np.array([10,20,30,40,50])
print(np.random.choice(arr))

20
