# Create a 1D array and print the third element.

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

Print the third element

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[2])

30


# Print the last element.

arr = np.array([5, 10, 15, 20, 25])

In [ ]:

arr = np.array([5, 10, 15, 20, 25])
print(arr[-1])

25


# Access an element from a 2D array.

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

Print 8

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[2,1])

8


# Access an element from a 3D array.

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

Print 7

In [ ]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr[1,1,0])

7


# Slice the first three elements.

arr = np.array([10,20,30,40,50])

In [ ]:

arr = np.array([10,20,30,40,50])
print(arr[:3])

[10 20 30]


# Slice from index 2 to the end.

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[2:])

[30 40 50]


# Slice a 2D array.
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

Print
[[20 30]
 [50 60]]

In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])


print(arr[:2,1:])