# Create an empty array of size 5.


In [6]:
import numpy as np

arr = np.empty(5)
print(arr)

[4.24399158e-314 9.88131292e-324 0.00000000e+000 0.00000000e+000
 0.00000000e+000]


# Create an array filled with 7.

In [7]:
arr = np.full((3,3), 7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# Create an array of even numbers from 2 to 20.

In [8]:
arr = np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


# Create a 4×4 matrix of zeros.

In [9]:
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
