Random Functions

In [60]:
import numpy as np

In [61]:
#1)
np.random.rand(5)

array([0.90670799, 0.93905365, 0.56793207, 0.94249818, 0.56597044])

In [62]:
#2)

a = [0, 1]

arr = np.random.choice(a, size=(10, 10), replace=True, p=[0.8, 0.2])

print(arr)

[[1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0]
 [1 1 1 0 0 0 0 1 0 0]
 [0 0 0 1 1 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]


In [63]:
#3)
np.random.randint(1,10,(2,3),np.int8)

array([[5, 7, 6],
       [1, 9, 5]], dtype=int8)

In [64]:
np.random.randint(1,90,(10,10),np.int8)

array([[11, 23, 88, 63,  7, 57, 50, 64, 45, 77],
       [51,  8, 14,  6, 69, 33, 24, 27, 10, 43],
       [28, 56, 10, 52, 85, 14, 75, 21, 73, 74],
       [88, 14, 81, 77, 54, 15, 26,  2, 88, 42],
       [23, 29, 59,  9, 47, 25, 73,  4, 89, 87],
       [61, 21, 22, 67,  6, 58,  9, 71, 23, 47],
       [85, 73, 74, 28, 11, 59, 54, 31,  5, 31],
       [16, 30, 31, 56, 38, 54, 49, 78, 39, 87],
       [ 8, 86, 11,  4, 45, 32,  7, 17, 29, 48],
       [37, 49, 89, 13, 23, 77, 53, 68, 56, 45]], dtype=int8)

In [65]:
np.random.randint(90)

6

In [66]:
np.random.randint(5,10)

8

In [67]:
np.random.randint(5,10,8)

array([6, 6, 7, 5, 7, 8, 5, 8], dtype=int32)