Random Functions

In [133]:
import numpy as np

In [134]:
#1)
np.random.rand(5)

array([0.16619157, 0.55681679, 0.58844191, 0.61971947, 0.25600715])

In [135]:
#2)

a = [0, 1]

arr = np.random.choice(a, size=(10, 10), replace=True, p=[0.8, 0.2])

print(arr)

[[0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [136]:
#3)
np.random.randint(1,10,(2,3),np.int8)

array([[3, 5, 7],
       [8, 7, 2]], dtype=int8)

In [137]:
np.random.randint(1,90,(10,10),np.int8)

array([[34,  6, 63, 26, 68,  6, 18, 33, 40, 39],
       [ 1, 89, 41, 39, 21, 69, 22, 48, 54, 45],
       [87, 17, 39, 75, 71, 59, 67, 51,  5, 59],
       [21,  5, 81, 79, 73, 81, 15, 14, 43, 33],
       [ 5, 77, 10, 88, 77, 69, 27, 31, 26, 51],
       [49, 31, 49, 77,  4, 10, 40, 10, 43, 24],
       [38, 81, 79, 33, 64, 84, 16,  7, 63, 73],
       [84,  7, 11, 42,  9, 63, 76, 11, 70, 26],
       [67, 47, 27, 62, 77, 72, 34, 13, 62, 49],
       [23, 34, 46, 29, 61, 26, 15, 44, 65, 59]], dtype=int8)

In [138]:
np.random.randint(90)

37

In [139]:
np.random.randint(5,10)

7

In [140]:
np.random.randint(5,10,8)

array([7, 6, 5, 6, 5, 5, 7, 6], dtype=int32)

In [141]:
a = [1,2,3,4,[5,6,7],8,9]
print(a[0:4])

print(a[4][1])

[1, 2, 3, 4]
6


In [142]:
arr = np.array([1,2,4,5,6,7,7,8,8])
arr[2]


np.int64(4)

In [143]:
arr = np.array([[1,2,4,5],[6,7,7,8]])
print(arr[0,0])

1


In [144]:
print(arr[0:2,0])

[1 6]


In [145]:
print(arr[0:2,0:2])

[[1 2]
 [6 7]]


In [146]:
print(arr[0:3,1:3])

[[2 4]
 [7 7]]


Fancy Indexing

In [147]:
a = np.array([1,2,3,4,6,7,8])
b = [1,3,4]
a[b]

array([2, 4, 6])

In [148]:
import numpy as np

arr = np.array([[[1, 2, 4, 5],
                 [6, 7, 7, 8],
                 [9, 8, 6, 4]]])

arr[0, 2, 1]


np.int64(8)

In [149]:
arr=np.array([1,2,3,4,6,7,8,9,10])
a=[2,3,4]
arr[a]
print(arr[arr<5])

[1 2 3 4]


In [150]:
ap = np.array([2,3,4,5,6,7,8,9,17,59])
print(ap+3)

[ 5  6  7  8  9 10 11 12 20 62]


In [151]:
ap = np.array([2,3,4,5,6,7,8,9,17,59])
print(ap*9)

[ 18  27  36  45  54  63  72  81 153 531]


In [152]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,7])

c = a+b

print(c)

[ 6  8 10 11]


Iterating through arrays

In [153]:
arr = np.array([[[1,2,3,4,6,5]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
6
5


In [154]:
arr = np.array([[[1,2,3,4,6,5]]])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 6
(0, 0, 5) 5


In [155]:
arr = np.array([[[1,2,3,4,6,5],[2,3,5,6,7,8]]])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 6
(0, 0, 5) 5
(0, 1, 0) 2
(0, 1, 1) 3
(0, 1, 2) 5
(0, 1, 3) 6
(0, 1, 4) 7
(0, 1, 5) 8
