Random Functions

In [18]:
import numpy as np

In [19]:
#1)
np.random.rand(5)

array([0.80381167, 0.92324843, 0.03429149, 0.46573237, 0.51472424])

In [20]:
#2)

a = [0, 1]

arr = np.random.choice(a, size=(10, 10), replace=True, p=[0.8, 0.2])

print(arr)

[[0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1 0 0]]


In [21]:
#3)
np.random.randint(1,10,(2,3),np.int8)

array([[3, 5, 6],
       [8, 8, 2]], dtype=int8)

In [22]:
np.random.randint(1,90,(10,10),np.int8)

array([[27, 12, 43,  5, 24, 75, 56,  9, 89, 81],
       [67, 40, 53, 73, 75, 47, 89, 56, 86, 50],
       [39, 34, 88, 79, 33, 33, 13, 41, 54, 71],
       [20, 82, 34, 64, 28, 29, 47, 55, 12, 88],
       [22, 32,  9, 54,  2, 55, 31, 55, 44, 29],
       [74, 29, 25, 70, 71, 68, 62, 72, 20, 82],
       [30, 79, 31, 64, 39, 17, 47, 58, 29, 19],
       [68, 75,  9, 10,  3, 35, 69, 36, 65, 28],
       [24,  6, 50, 19, 87, 75, 60, 81, 73, 13],
       [23, 37, 20, 67, 44, 14, 49,  6, 89,  3]], dtype=int8)