Random Functions

In [ ]:
import numpy as np

In [233]:
#1)
np.random.rand(5)

array([0.43256972, 0.51194252, 0.58245879, 0.79451587, 0.53385265])

In [234]:
#2)

a = [0, 1]

arr = np.random.choice(a, size=(10, 10), replace=True, p=[0.8, 0.2])

print(arr)

[[0 1 0 0 1 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 1 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1 1 0]
 [1 1 0 0 0 1 0 0 0 1]
 [0 1 0 1 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]]


In [235]:
#3)
np.random.randint(1,10,(2,3),np.int8)

array([[8, 7, 8],
       [5, 7, 2]], dtype=int8)

In [236]:
np.random.randint(1,90,(10,10),np.int8)

array([[33, 38, 50, 77, 46, 48,  7, 34, 18, 81],
       [69, 44, 89, 24, 67, 30, 37, 21, 12, 82],
       [17, 39, 68, 48, 44, 51, 57, 61,  6, 63],
       [33,  1, 49, 21, 67, 82, 42, 71, 76, 14],
       [45, 73, 11, 68, 15, 68, 23, 77, 70, 82],
       [67, 33, 44, 57, 43, 36, 67, 77, 38, 38],
       [12, 86, 64, 24, 73, 16, 22, 16, 82, 33],
       [10, 83, 61,  3, 48,  3, 21, 68, 48, 15],
       [47, 55, 28, 45, 19, 84, 67, 47, 14, 86],
       [44, 46, 11, 85, 87, 59, 13, 19, 33, 87]], dtype=int8)

In [237]:
np.random.randint(90)

59

In [238]:
np.random.randint(5,10)

5

In [239]:
np.random.randint(5,10,8)

array([9, 6, 9, 8, 9, 8, 6, 9], dtype=int32)

In [ ]:
a = [1,2,3,4,[5,6,7],8,9]
print(a[0:4])

print(a[4][1])

[1, 2, 3, 4]
6


In [ ]:
arr = np.array([1,2,4,5,6,7,7,8,8])
arr[2]


np.int64(4)

In [ ]:
arr = np.array([[1,2,4,5],[6,7,7,8]])
print(arr[0,0])

1


In [ ]:
print(arr[0:2,0])

[1 6]


In [ ]:
print(arr[0:2,0:2])

[[1 2]
 [6 7]]


In [245]:
print(arr[0:3,1:3])

[[2 4]
 [7 7]]


Fancy Indexing

In [ ]:
a = np.array([1,2,3,4,6,7,8])
b = [1,3,4]
a[b]

array([2, 4, 6])

In [247]:
import numpy as np

arr = np.array([[[1, 2, 4, 5],
                 [6, 7, 7, 8],
                 [9, 8, 6, 4]]])

arr[0, 2, 1]


np.int64(8)

In [ ]:
arr=np.array([1,2,3,4,6,7,8,9,10])
a=[2,3,4]
arr[a]
print(arr[arr<5])

[1 2 3 4]
