Random Functions

In [39]:
import numpy as np

In [40]:
#1)
np.random.rand(5)

array([0.29922377, 0.35657397, 0.18890376, 0.11278434, 0.84010707])

In [41]:
#2)

a = [0, 1]

arr = np.random.choice(a, size=(10, 10), replace=True, p=[0.8, 0.2])

print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 1 1 0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0]]


In [42]:
#3)
np.random.randint(1,10,(2,3),np.int8)

array([[5, 2, 7],
       [7, 6, 8]], dtype=int8)

In [43]:
np.random.randint(1,90,(10,10),np.int8)

array([[ 5, 73,  7, 37, 66, 22, 76, 11, 16,  3],
       [11, 46, 67, 31, 75, 39, 49, 15, 50, 26],
       [78, 19, 46, 48, 35, 22, 20, 10, 31, 52],
       [18, 57,  9, 79, 68, 12, 59, 54, 56, 78],
       [16, 54, 69, 76, 35, 47, 21, 78, 14, 20],
       [30, 52, 31, 53, 78, 17,  9, 32, 62, 76],
       [64, 75, 88, 37, 88, 15, 16,  2, 83, 44],
       [62, 82, 17,  6, 73, 45, 25, 14, 24,  1],
       [70, 46, 36, 79,  2, 12, 60, 67, 11, 25],
       [34, 69, 51, 33, 22, 11, 12, 67, 76, 33]], dtype=int8)

In [44]:
np.random.randint(90)

45

In [45]:
np.random.randint(5,10)

5

In [46]:
np.random.randint(5,10,8)

array([9, 9, 5, 8, 8, 9, 8, 6], dtype=int32)

In [47]:
a = [1,2,3,4,[5,6,7],8,9]
print(a[0:4])

print(a[4][1])

[1, 2, 3, 4]
6


In [48]:
arr = np.array([1,2,4,5,6,7,7,8,8])
arr[2]


np.int64(4)

In [49]:
arr = np.array([[1,2,4,5],[6,7,7,8]])
print(arr[0,0])

1


In [50]:
print(arr[0:2,0])

[1 6]


In [51]:
print(arr[0:2,0:2])

[[1 2]
 [6 7]]


In [52]:
print(arr[0:3,1:3])

[[2 4]
 [7 7]]


Fancy Indexing

In [53]:
a = np.array([1,2,3,4,6,7,8])
b = [1,3,4]
a[b]

array([2, 4, 6])

In [54]:
import numpy as np

arr = np.array([[[1, 2, 4, 5],
                 [6, 7, 7, 8],
                 [9, 8, 6, 4]]])

arr[0, 2, 1]


np.int64(8)

In [55]:
arr=np.array([1,2,3,4,6,7,8,9,10])
a=[2,3,4]
arr[a]
print(arr[arr<5])

[1 2 3 4]


In [56]:
ap = np.array([2,3,4,5,6,7,8,9,17,59])
print(ap+3)

[ 5  6  7  8  9 10 11 12 20 62]


In [57]:
ap = np.array([2,3,4,5,6,7,8,9,17,59])
print(ap*9)

[ 18  27  36  45  54  63  72  81 153 531]


In [58]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,7])

c = a+b

print(c)

[ 6  8 10 11]
