Slicing

Slicing With List

In [15]:
a = [1,2,3,4,[5,6,7],8,9]
print(a[0:4])

print(a[4][1])

[1, 2, 3, 4]
6


Slicing With Array

In [16]:
import numpy as np

In [17]:
arr = np.array([1,2,4,5,6,7,7,8,8])
arr[2]


np.int64(4)

In [18]:
arr = np.array([[1,2,4,5],[6,7,7,8]])
print(arr[0,0])

1


In [19]:
print(arr[0:2,0])

[1 6]


In [20]:
print(arr[0:2,0:2])

[[1 2]
 [6 7]]


Fancy Indexing

In [21]:
a = np.array([1,2,3,4,6,7,8])
b = [1,3,4]
a[b]

array([2, 4, 6])

In [22]:
arr=np.array([1,2,3,4,6,7,8,9,10])
a=[2,3,4]
arr[a]
print(arr[arr<5])

[1 2 3 4]
