In [356]:
import numpy as np

In [357]:
data = np.array([[1,2,3],[4,5,6]])
data.flatten()


array([1, 2, 3, 4, 5, 6])

In [358]:
data.flatten(order='c')

array([1, 2, 3, 4, 5, 6])

In [359]:
data.flatten(order='f')

array([1, 4, 2, 5, 3, 6])

In [360]:
data.flatten(order='k')

array([1, 2, 3, 4, 5, 6])

In [361]:
data.flatten(order='a')

array([1, 2, 3, 4, 5, 6])

In [362]:
data.ravel()

array([1, 2, 3, 4, 5, 6])

In [363]:
data.ravel(order='f')

array([1, 4, 2, 5, 3, 6])

In [364]:
data.ravel(order='c')

array([1, 2, 3, 4, 5, 6])

In [365]:
data.ravel(order='k')

array([1, 2, 3, 4, 5, 6])

In [366]:
data.ravel(order='a')

array([1, 2, 3, 4, 5, 6])

In [367]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,4)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [368]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2)
print(arr1)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [369]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,2)
print(arr1)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [370]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2,axis=1)
print(arr1)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [371]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.transpose(arr1)
arr3

array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [372]:
arr = np.array([1,5,6,7,8,2,4])
np.sort(arr)

array([1, 2, 4, 5, 6, 7, 8])

In [373]:
arr2 = np.array([[1,3,9,4],[5,6,7,8]])
np.sort(arr2)

array([[1, 3, 4, 9],
       [5, 6, 7, 8]])

In [374]:
arr = np.array([1,5,6,7,8,2,4])
np.sort(arr[::-1])

array([1, 2, 4, 5, 6, 7, 8])