In [482]:
import numpy as np

In [483]:
data = np.array([[1,2,3],[4,5,6]])
data.flatten()


array([1, 2, 3, 4, 5, 6])

In [484]:
data.flatten(order='c')

array([1, 2, 3, 4, 5, 6])

In [485]:
data.flatten(order='f')

array([1, 4, 2, 5, 3, 6])

In [486]:
data.flatten(order='k')

array([1, 2, 3, 4, 5, 6])

In [487]:
data.flatten(order='a')

array([1, 2, 3, 4, 5, 6])

In [488]:
data.ravel()

array([1, 2, 3, 4, 5, 6])

In [489]:
data.ravel(order='f')

array([1, 4, 2, 5, 3, 6])

In [490]:
data.ravel(order='c')

array([1, 2, 3, 4, 5, 6])

In [491]:
data.ravel(order='k')

array([1, 2, 3, 4, 5, 6])

In [492]:
data.ravel(order='a')

array([1, 2, 3, 4, 5, 6])

In [493]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,4)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [494]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2)
print(arr1)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [495]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,2)
print(arr1)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [496]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2,axis=1)
print(arr1)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [497]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.transpose(arr1)
arr3

array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [498]:
arr = np.array([1,5,6,7,8,2,4])
np.sort(arr)

array([1, 2, 4, 5, 6, 7, 8])

In [499]:
arr2 = np.array([[1,3,9,4],[5,6,7,8]])
np.sort(arr2)

array([[1, 3, 4, 9],
       [5, 6, 7, 8]])

In [500]:
arr = np.array([1,5,6,7,8,2,4])
np.sort(arr[::-1])

array([1, 2, 4, 5, 6, 7, 8])

In [501]:
# arr = np.array([1,2,3,4,4,4,5,72,8,94,5,6])
# arr = np.array([[9,8,7,6,5,4,3,2,1]])
arr = np.array([[1,2,3,4,5,6,7,8,9]])

# print(np.sort(arr))

print(np.sort(arr,axis=-1,kind='stablesort'))

[[1 2 3 4 5 6 7 8 9]]


In [502]:
arr = np.array([1,2,3,4,4,4,5,72,8,94,5,6])
np.where(arr%2==0,"even",arr)

array(['1', 'even', '3', 'even', 'even', 'even', '5', 'even', 'even',
       'even', '5', 'even'], dtype='<U21')

In [503]:
arr = np.array([1,2,3,4,4,4,5,72,8,94,5,6])
np.where(arr%2==0)

(array([ 1,  3,  4,  5,  7,  8,  9, 11]),)

In [504]:
np.delete(arr,3)

array([ 1,  2,  3,  4,  4,  5, 72,  8, 94,  5,  6])

In [505]:
np.delete(arr,[1,2,4,5,7])

array([ 1,  4,  5,  8, 94,  5,  6])