In [213]:
import numpy as np

In [214]:
data = np.array([[1,2,3],[4,5,6]])
data.flatten()


array([1, 2, 3, 4, 5, 6])

In [215]:
data.flatten(order='c')

array([1, 2, 3, 4, 5, 6])

In [216]:
data.flatten(order='f')

array([1, 4, 2, 5, 3, 6])

In [217]:
data.flatten(order='k')

array([1, 2, 3, 4, 5, 6])

In [218]:
data.flatten(order='a')

array([1, 2, 3, 4, 5, 6])

In [219]:
data.ravel()

array([1, 2, 3, 4, 5, 6])

In [220]:
data.ravel(order='f')

array([1, 4, 2, 5, 3, 6])

In [221]:
data.ravel(order='c')

array([1, 2, 3, 4, 5, 6])

In [222]:
data.ravel(order='k')

array([1, 2, 3, 4, 5, 6])

In [223]:
data.ravel(order='a')

array([1, 2, 3, 4, 5, 6])

In [224]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,4)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [225]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2)
print(arr1)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [226]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,2)
print(arr1)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [227]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2,axis=1)
print(arr1)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
