In [81]:
import numpy as np

In [82]:
data = np.array([[1,2,3],[4,5,6]])
data.flatten()


array([1, 2, 3, 4, 5, 6])

In [83]:
data.flatten(order='c')

array([1, 2, 3, 4, 5, 6])

In [84]:
data.flatten(order='f')

array([1, 4, 2, 5, 3, 6])

In [85]:
data.flatten(order='k')

array([1, 2, 3, 4, 5, 6])

In [86]:
data.flatten(order='a')

array([1, 2, 3, 4, 5, 6])

In [87]:
data.ravel()

array([1, 2, 3, 4, 5, 6])

In [88]:
data.ravel(order='f')

array([1, 4, 2, 5, 3, 6])

In [89]:
data.ravel(order='c')

array([1, 2, 3, 4, 5, 6])

In [90]:
data.ravel(order='k')

array([1, 2, 3, 4, 5, 6])

In [91]:
data.ravel(order='a')

array([1, 2, 3, 4, 5, 6])