In [34]:
import numpy as np

In [35]:
data = np.array([[1,2,3],[4,5,6]])
data.flatten()


array([1, 2, 3, 4, 5, 6])

In [36]:
data.flatten(order='c')

array([1, 2, 3, 4, 5, 6])

In [37]:
data.flatten(order='f')

array([1, 4, 2, 5, 3, 6])

In [38]:
data.flatten(order='k')

array([1, 2, 3, 4, 5, 6])

In [39]:
data.ravel()

array([1, 2, 3, 4, 5, 6])