In [375]:
import numpy as np

In [376]:
data = np.array([[1,2,3],[4,5,6]])
data.flatten()


array([1, 2, 3, 4, 5, 6])

In [377]:
data.flatten(order='c')

array([1, 2, 3, 4, 5, 6])

In [378]:
data.flatten(order='f')

array([1, 4, 2, 5, 3, 6])

In [379]:
data.flatten(order='k')

array([1, 2, 3, 4, 5, 6])

In [380]:
data.flatten(order='a')

array([1, 2, 3, 4, 5, 6])

In [381]:
data.ravel()

array([1, 2, 3, 4, 5, 6])

In [382]:
data.ravel(order='f')

array([1, 4, 2, 5, 3, 6])

In [383]:
data.ravel(order='c')

array([1, 2, 3, 4, 5, 6])

In [384]:
data.ravel(order='k')

array([1, 2, 3, 4, 5, 6])

In [385]:
data.ravel(order='a')

array([1, 2, 3, 4, 5, 6])

In [386]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,4)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [387]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2)
print(arr1)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [388]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,2)
print(arr1)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [389]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr1 = np.split(arr,2,axis=1)
print(arr1)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [390]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.transpose(arr1)
arr3

array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [391]:
arr = np.array([1,5,6,7,8,2,4])
np.sort(arr)

array([1, 2, 4, 5, 6, 7, 8])

In [392]:
arr2 = np.array([[1,3,9,4],[5,6,7,8]])
np.sort(arr2)

array([[1, 3, 4, 9],
       [5, 6, 7, 8]])

In [393]:
arr = np.array([1,5,6,7,8,2,4])
np.sort(arr[::-1])

array([1, 2, 4, 5, 6, 7, 8])

In [394]:
# arr = np.array([1,2,3,4,4,4,5,72,8,94,5,6])
# arr = np.array([[9,8,7,6,5,4,3,2,1]])
arr = np.array([[1,2,3,4,5,6,7,8,9]])

# print(np.sort(arr))

print(np.sort(arr,axis=-1,kind='stablesort'))

[[1 2 3 4 5 6 7 8 9]]
